### PR TITLE
Issue/1438 Added Auto GZip compress to gateway

### PR DESCRIPTION
**Pull request by t83714**
### What this PR does

Issue/1438 Added Auto GZip compress to gateway
Used `compression` lib: https://github.com/expressjs/compression
Checked the source code. By default, It can:
- Only compress `compressible` content by looking at `Content-type` header of res
  - It uses [compressible](https://www.npmjs.com/package/compressible) for this
- Will add `Accept-Encoding` [Vary](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Vary) header (and [this](https://stackoverflow.com/questions/43217103/google-cdn-random-not-serving-gzip-content)) so CDN can serve non-compress copy to upsupported client and compressed copy to supported client.
- Will only compress if client accept gzip or deflate encoding (by looking at Accept Encoding from request)

### Checklist

-   [x] Unit tests aren't applicable (delete one)
-   [x] I've updated CHANGES.md with what I changed.
-   [x] I've linked this PR to an issue in ZenHub (or there is no issue) and dragged it to the _Pull Request_ column
-   [x] There are sufficient comments for my code to be understandable - and I realise reviewers will pull me up on it if not!

### CODE REVIEW

**Comment by AlexGilleran** [comment]
It mostly works but seems to GZIP some things and not others :/.

- Responses from the web server are gzipped
- Most API responses aren't GZIPped - e.g. https://issue-1438.dev.magda.io/api/v0/search/datasets?start=0&limit=10
- ... but some are, e.g. https://issue-1438.dev.magda.io/api/v0/search/region-types

Weird, those last two both have `content-type: application/json` 🤔

**Comment by AlexGilleran** [comment]
Maybe it's the size of the latter? 🤔

**Comment by t83714** [comment]
@AlexGilleran 
Yes. The source code indicates it only gzip content if it's bigger enough --- too small response you won't be benefited too much from compress (and considering the overhead might not worth it )
The default value it's 1024. 
The lib will auto check this by looking at Content-Length header.
But it's configurable.

**Comment by AlexGilleran** [comment]
But it's the other way around - the big one doesn't zip and the small one does 😢

**Comment by t83714** [comment]
...argh...if so, I think we just discovered a bug here.
emm... from the source code doesn't suggest that way:
https://github.com/expressjs/compression/blob/7ebf291087d69156df4b086e2020e660a1dffb17/index.js#L158
I will have a few tests as well.

**Comment by AlexGilleran** [comment]
@t83714 don't worry I got it the wrong way around 😂

**Comment by AlexGilleran** [comment]
Yep confirmed that once I've put some data in, https://issue-1438.dev.magda.io/api/v0/search/datasets?start=0&limit=10 has GZIP 🎉

**Pull request merged**
