### PR TITLE
Issue/1266 updated chart icons

### PR DESCRIPTION
**Pull request by sukhrajghuman**
### What this PR does
Changed chart icons and active/hover states for them

### Checklist

-   [x] There are unit tests to verify my changes are correct | Unit tests aren't applicable (delete one)
-   [x] I've updated CHANGES.md with what I changed.
-   [x] I've linked this PR to an issue in ZenHub (or there is no issue) and dragged it to the _Pull Request_ column
-   [x] There are sufficient comments for my code to be understandable - and I realise reviewers will pull me up on it if not!

### CODE REVIEW

**Comment by tkeuneman** [comment]
Can you make it so on hover, the light purple border appears, but the colours don't invert on hover? That will stop the below from happening:
screen shot 2018-06-29 at 2 06 20 pm

Also, can you replace hover tooltip text with the following: Bar chart, Pie chart, Scatter chart, Line chart

**Comment by sukhrajghuman** [comment]
@tkeuneman should be good to go now 👍

**Comment by sukhrajghuman** [comment]
oh yep will delete

**Comment by tkeuneman** [comment]
Lemme know when I can have a look :)

**Comment by tkeuneman** [comment]
😸fect (purrrfect)

**Pull request merged**
