### PR TITLE
Removed horizontal scrollbar on distribution license element

### LINKED ISSUE #2468: Distribution-level license component has an unnecessary horizontal scrollbar
**Describe the bug**
In the add dataset flow, when setting licenses at a distribution level, the component that appears for every distribution has a horizontal scrollbar.

i.e. this individual component:
image

that appears here:

image

**To Reproduce**

1. Go to /dataset/add and add at least one file
2. Progress through the add dataset flow to page 4 (Access and Use)
3. Scroll down to "What type of license should be applied to these files?" and select "Distribution (or file) Level License"
4. Hover over one of the distributions and try to scroll sideways.

**Expected behavior**
There should be no horizontal scroll bar.

**Other details**
Present on a 13 inch macbook in Firefox.

### PR DESCRIPTION
**Pull request by AlexGilleran**
### What this PR does

Fixes #2468 

Just removed the `overflow: auto`, seems to work fine (it's the right width, not sure why its scroll-bars-ing).

### Checklist

-   [x] There are unit tests to verify my changes are correct or unit tests aren't applicable
-   [x] I don't think this really warrants changes
-   [x] I've linked this PR to an issue in ZenHub (core dev team only)

### CODE REVIEW

**Comment by t83714** [comment]
it seems once you switch to custom license, the input box goes over the container now: 
image

**Comment by AlexGilleran** [comment]
🤔 ohhhh. Ok cool thanks 👍

**Comment by t83714** [comment]
@AlexGilleran It seems the long filename is not wrapping now. 
Is there an easy way to fix it?

**Comment by AlexGilleran** [comment]
Ready for another look @t83714

**Pull request merged**
