### PR TITLE
Issue/2249 New Add Dataset Page Design

### LINKED ISSUE #2249: Align "Add a Dataset" screen with new designs
### Problem description
Style the first "Add a Dataset" page to match the new designs.

https://app.zeplin.io/project/5cff0c2b6308535da4f2dfe8/screen/5cff0cedcb970515fcbb9b1b

image

Just styling changes, no need for new interactions.

### Needs Clarification
- What should happen to the buttons on hover?

### Acceptance Criteria
- Colour of the top rows should be configurable based on an SCSS variable

### Out of Scope
- Changing the header

### PR DESCRIPTION
**Pull request by t83714**
### What this PR does

Fixes #2249
- New Add Dataset Page Design

Test site URL: 

~https://issue-2249.dev.magda.io/dataset/add~
https://issue-2250.dev.magda.io/

image

### Checklist

-   [x] unit tests aren't applicable
-   [x] I've updated CHANGES.md with what I changed.
-   [x] I've linked this PR to an issue in ZenHub (core dev team only)

### CODE REVIEW

**Comment by AlexGilleran** [comment]
Looks like it's missing the save icon?

**Comment by t83714** [comment]
> * Looks like it's missing the save icon?
> * I think the backgrounds are supposed to be full-width

- Yeah somehow I downloaded a blank one oval image~ Will replace that icon~
- Should only make this page full-width or make all other pages full-width as well? @AlexGilleran

**Comment by AlexGilleran** [comment]
@t83714 the _content_ of the page should still be the same width it always was, it's just the background that needs to be full-width - a.k.a.

image

These white bars shouldn't be at the side of the page :).

**Comment by t83714** [comment]
@AlexGilleran I've merged this one into 2250. Will close this & update it on 2250

**Comment by charliemce** [comment]
screenshot-issue-2250 dev magda io-2019 06 18-22-42-32
screenshot-issue-2250 dev magda io-2019 06 18-19-16-46 (1)
screenshot-issue-2250 dev magda io-2019 06 18-19-15-57 (1)
screenshot-issue-2250 dev magda io-2019 06 18-19-15-29 (1)
screenshot-issue-2250 dev magda io-2019 06 18-19-14-46 (1)

**Comment by charliemce** [comment]
Left some comments annotated above as was the quickest way for me - hope this works for you - let me know if you'd like to clarify anything. I also would like to see some padding on left & right side of all pages (let's try 80px++)

**Comment by t83714** [comment]
@charliemce Thanks for the feedback~ 👍 
Some of the comment probably not for this issue (this issue is only for the Add Dataset page the first page only)~
Will copy your comment to the relevent ticket (if not for this PR) and update program (if it's for this ticket) accordingly~

**Comment by t83714** [comment]
Created a separate ticket #2258 for some feedback items.
The last two screenshots (icons) will be addressed on PR for #2250 
Close this PR as it's already merged into https://github.com/magda-io/magda/pull/2257

**Pull request closed without merging**
