### PR TITLE
Made CORS work for localhost connecting to dev.magda.io again

### LINKED ISSUE #1743: Can't access dev.magda.io API when running from localhost or preview
### Problem description
Because we're returning `*` as the origin on dev but also including credentials in the fetch request, chrome is getting v. cranky:

```
Failed to load https://dev.magda.io/api/v0/auth/users/whoami: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'. Origin 'http://localhost:6108' is therefore not allowed access.
```

We should make it so that in dev (and definitely NOT in prod), the `origin` header gets reflected back as the Access-Control-Allow-Origin header.

### PR DESCRIPTION
**Pull request by AlexGilleran**
### What this PR does
Makes the gateway reflect the CORS origin for preview and dev so that we can continue using it as the API when running locally or in ui-only previews. This involved changing the config and also stripping the CORS plugin out of the scala APIs.

Fixes #1743 

### Checklist

-   [x] There are unit tests to verify my changes are correct or unit tests aren't applicable
-   [x] I've updated CHANGES.md with what I changed.
-   [x] I've linked this PR to an issue in ZenHub (core dev team only)
-   [x] I've assigned this PR to someone (if you don't know who to assign it to, pick @AlexGilleran)

### CODE REVIEW

**Comment by t83714** [comment]
@AlexGilleran 
- Tested using a local web-client connect to the gitlab deployment.
It looks good 👍  And `access-control-allow-origin` now show as my localhost
image
- Also tested put the instance behind a password. Didn't find any issues for both Chrome & Safari
- Only issue is when you connect to the gitlab deployment from a local web-client, the map preview seems not work:
```
Refused to display 'https://issue-1743-make-cors-header-reflect-origin-in-dev.dev.magda.io/preview-map/#mode=preview&hideExplorerPanel=1' in a frame because it set 'X-Frame-Options' to 'sameorigin'.
```
But I guess we set that option for security reason, right?

**Comment by t83714** [comment]
By the way, the instance is now behinds a password. if you want to have a try, the username is `magda` & password is `Faegaehie7chaiye `

**Comment by AlexGilleran** [comment]
@t83714 I've turned frameguard off on previews too, so now you should be able to run on localhost and connect to the preview URL with maps working again 👍

**Comment by t83714** [comment]
Tested and preview map works well at local now 👍 
Merging~

**Pull request merged**
