### PR TITLE
Modified layout of distribution page

### PR DESCRIPTION
**Pull request by adamzerella**
### What this PR does
- Added new separator component, mimicking the divider component
- Adds download button
- Updates text
- Move around layout following Figma specs.

# Preview:
image

### Checklist

-   [x] Unit tests aren't applicable (delete one)
-   [x] I've updated CHANGES.md with what I changed.
-   [x] I've linked this PR to an issue in ZenHub (or there is no issue) and dragged it to the _Pull Request_ column
-   [x] There are sufficient comments for my code to be understandable - and I realise reviewers will pull me up on it if not!

### CODE REVIEW

**Comment by adamzerella** [comment]
@tkeuneman Let me know if the "Data Preview" title on the distribution visual is bad

**Comment by tkeuneman** [comment]
I think I'll change the source text to match data preview but need to double check

**Comment by tkeuneman** [comment]
sugar_exemptions_1922-1923_data_gov_au

**Comment by adamzerella** [comment]
@tkeuneman Updated branch from feedback:

image

I don't think the breadcrumbs are an issue as I never removed them and branched off of the latest `master` head? I think merging it into master will bring back the breadcrumbs.

**Comment by tkeuneman** [comment]
Cool beans. Looks good!

**Pull request merged**
