### PR TITLE
Issue/1275 markdown not rendering properly again

### PR DESCRIPTION
**Pull request by adamzerella**
### What this PR does
"De-styles" `ul`, `li`, `hr` and other related tags to plaintext. Previous fixes didn't include dataset detail pages, only summaries.

I challenge @tkeuneman to find other datasets with broken markdown rendering

### Checklist

-   [x]  Unit tests aren't applicable (delete one)
-   [x] I've updated CHANGES.md with what I changed.
-   [x] I've linked this PR to an issue in ZenHub (or there is no issue) and dragged it to the _Pull Request_ column
-   [x] There are sufficient comments for my code to be understandable - and I realise reviewers will pull me up on it if not!

# Previews:
image

image

image

### CODE REVIEW

**Comment by AlexGilleran** [comment]
... are we sure? I think it makes way more sense to keep the bullet points in there in all cases, and I don't think we should be interfering with markdown rendering on the dataset page.

**Comment by AlexGilleran** [comment]
@tkeuneman ?

**Comment by tkeuneman** [comment]
Thanks for the great pick up @AlexGilleran. Keeping height restrictions instead.

**Comment by adamzerella** [comment]
@AlexGilleran Updated PR, markdown only renders on dataset summaries again, lists retain their `-`.

# Preview:

## Dataset summary
image

## Dataset page
image

**Pull request merged**
