### PR TITLE
Org search

### PR DESCRIPTION
**Pull request by chloeleichen**
### What this PR does
Some improvement for org search page
screen shot 2018-07-11 at 2 28 03 pm

### Checklist

-   [x] There are unit tests to verify my changes are correct | Unit tests aren't applicable (delete one)
-   [x] I've updated CHANGES.md with what I changed.
-   [x] I've linked this PR to an issue in ZenHub (or there is no issue) and dragged it to the _Pull Request_ column
-   [x] There are sufficient comments for my code to be understandable - and I realise reviewers will pull me up on it if not!

### CODE REVIEW

**Comment by AlexGilleran** [comment]
Code looks ok.

Few problems:
image
1. There's an extra space at the beginning of the search that I didn't put in there.
2. The "Clear Search" button doesn't actually clear the search - it updates the URL but nothing happens on screen. You can see it at https://org-search.dev.magda.io/organisations?page=1&q=CSIRO.

@tkeuneman do you want to review this visually? https://org-search.dev.magda.io/organisations

**Comment by tkeuneman** [comment]
Just a couple of quick tweaks:
- [ ] Remove the brackets around the dataset count in the Organisation page, so it goes 
> 12 datasets
as opposed to 
> [12] datasets
- [ ] Check the padding between the header and the breadcrumbs. Seems tighter than other pages. You'll have to add 32pt at the top padding in order to make it match the rest of the pages
- [ ] Clicking or tapping on the search icon does not conduct the search. Works fine with 'enter'
- [ ] Clear search stays highlighted on mobile, when I haven't selected anything as well as when I've just conducted a search. So, when present, it's always highlighted
- [ ] On mobile, when I hit the 'complete action' on the keyboard ( -> for Android, 'return' on iOS), the keyboard doesn't go away. You have to manually dismiss this. This doesn't happen on the homepage search (it dismisses once the search runs), so you can copy this.
screenshot_20180712-193722

**Comment by chloeleichen** [comment]
re keyboard dismissal:
tested on iPhone: pressing "done" key dismiss the keyboard.
Need to test on android

**Comment by tkeuneman** [comment]
I can test this if you like. :)

**Comment by tkeuneman** [comment]
When I conduct a search, there's 42 results, but it shows the default pagination (when it should be two)

screen shot 2018-07-13 at 11 15 38 am

**Comment by chloeleichen** [comment]
updated!

**Pull request merged**
