### PR TITLE
Issue/2263 New Accrual Periodicity Recurrence Input

### LINKED ISSUE #2263: Details And Contents Page - Item 3 New Recurrence Input
Applied new design to all dropdown box on `Details And Contents Page`.

See screenshot below:

> image

- Estimate: 5

More logic description will follow before we start to work on this

### Update on 2nd July 2019:

**The custom Recurrence Input is actually supporting question `How frequently is the dataset updated? ` rather than question `What time period does the dataset cover?`**.

The custom Recurrence Input will be shown to the user when the user selects the `Custom...` option from the dropdown.

image

### Update on 2nd July 2019 re: Backend:
We will:
- Add a new string field named `accrualPeriodicityRecurrenceRule` (on `dcat-dataset-strings` aspect) that stores customized recurring info in `RRULE` format (part of iCalendar RFC). e.g. `RRULE:FREQ=WEEKLY;INTERVAL=5;UNTIL=20130130T230000Z;BYDAY=MO,FR`
- Will use an `RRULE` library e.g. [rrule.js](https://github.com/jakubroztocil/rrule) to parse the rule
- The system will only attempt to use this field to interpret the `accrual periodicity` info if `accrualPeriodicity` field is empty.

### PR DESCRIPTION
**Pull request by t83714**
### What this PR does

Fixes #2263
- New Accrual Periodicity Recurrence Input
- Added `accrualPeriodicityRecurrenceRule` field 
  - Use iCalendar Recurrence Rule RFC (The rule string will be something like:)
    - `RRULE:INTERVAL=6;FREQ=WEEKLY;BYDAY=MO,TH,SA,TU`
  - Adjustment on Backend registry api response converter
  - Make it index properly by indexer & inscrease index version no.
  - display properly on dataset page (only visible to admin)

@alyce Some slight changes on design:
- Custom Recurrence Input will be displayed on the side of the main dropdown
  - Popup could cause some logic issue.
- Removed the `apply` button as it will be auto saved (to avoid invalid data to be produced)

Update: Additional info:
- The dropdown needs to disappeared once the user selects an option.
- The Custom Recurrence Input will be shown in a popup and:
  - No close button
  - Will be a modal popup that user has to select the valid option before clicking the apply button to close it

#### Test site:

https://issue-2263.dev.magda.io/dataset/add

Note: To test indexer (i.e. save & index dataset), you need to create yourself an admin acct. You don't need this just to test the frontend UI.

### Checklist

-   [x] unit tests aren't applicable
-   [x] I've updated CHANGES.md with what I changed.
-   [x] I've linked this PR to an issue in ZenHub (core dev team only)

### CODE REVIEW

**Comment by alyce** [comment]
@t83714 thank you! Some comments:

**Page Focus**
On loading, the page focus seems to be jumping down to focus on the 'Dates and Updates' field. Is this a bug?

**Copy:**
Screen Shot 2019-07-05 at 2 25 00 pm
This should probably say "Which keywords best describe this dataset"

**Clear option**
Screen Shot 2019-07-05 at 2 26 13 pm
Can both the Keywords and Themes sections have the 'x' in the RH corner that clears all selections so someone can easily delete them all and start afresh

**Close frequency dropdown*
Screen Shot 2019-07-05 at 2 28 57 pm
There doesn't seem to be a way to close the Frequency dropdown once an option is selected

**Comment by t83714** [comment]
Todo:
- [ ] Page Focus Jumping issue
- [x] Update Keywords question title
- [ ] Add an `all clear` button to keywords & themes input
- [ ] Make custom recurrence input a popup and make dropdown hidden when select

**Comment by t83714** [comment]
@alyce 
The New Accrual Periodicity Recurrence Input is ready to have a look again:
Here is the test site link:
https://issue-2263.dev.magda.io/dataset/add

**Comment by t83714** [comment]
To @AlexGilleran :
@alyce is happy with the functionality and I think It's ready for code review now~ 👍

**Pull request merged**
