### PR TITLE
Performance Optimisation for Registry API

### LINKED ISSUE #749: Performance Optimisation for Registry API
A whole performance optimisation on registry API, to also solve the below problem.

It's possible for the Registry API to max out the CPU while doing very little
See this incident (if you can): https://app.google.stackdriver.com/incidents/0.kqbhybqnvvgj

Essentially the registry api was using its node's entire CPU - it was still responsible enough to survive livesness checks but slow enough that further-away stackdriver checks started to time out.

Restarting the pod fixed it.

Not sure what caused it or what the best mitigation is - perhaps more stringent liveness checks for now?

### PR DESCRIPTION
**Pull request by mwu2018**
### Fixes #749 Performance Optimisation for Registry API

In the old implementation, some actor's message processing tasks are long blocking calls (e.g. invalidating the web hook actor cache involves in database access, which might take very long time to complete.), which potentially may deplete resources and cause some unexpected results (They have not been verified though).

In the new implementation, instead of running long lasting tasks, InvalidateWebHookCacheThenProcess and RetryInactiveHooks, in an actor's receive function, those tasks are executed in a dedicated and fixed-size execution pool.  With this approach, an actor can respond to new message promptly. The approach also means that when an actor has finished processing a message, the task might not have been completed yet. For example, when registering a new subscriber, a response may be returned immediately but the underlying task, invalidating cache then notifying relevant events to the subscriber, may take quite some time to complete. This behaviour makes scala test harder to implement. The test implementation are also changed very significantly.

### Checklist

-   [x] There are unit tests to verify my changes are correct or unit tests aren't applicable
-   [x] I've updated CHANGES.md with what I changed.
-   [x] I've linked this PR to an issue in ZenHub (core dev team only)

### CODE REVIEW

**Comment by AlexGilleran** [comment]
Thanks @mwu2018 :). Can you please clean up the WIP commits (`git rebase -i master`) and add a title/description to the PR so I know what I'm looking at?

**Comment by mwu2018** [comment]
> Thanks @mwu2018 :). Can you please clean up the WIP commits (`git rebase -i master`) and add a title/description to the PR so I know what I'm looking at?

It is not ready yet. I will remember to remove those WIP this time :-) Will let you know when it is ready.

**Comment by AlexGilleran** [comment]
I'm finding that webhooks are being sent twice or three times simultaneously :( 

```
[INFO] [01/15/2019 06:17:45.987] [registry-api-akka.actor.default-dispatcher-12] [akka://registry-api/user/WebHookActor/WebHookActor-indexer-fa5cc0fd-e699-4824-9005-6f9bcf339d47] WebHook indexer Processing Some(190)-Some(200): STARTING
[INFO] [01/15/2019 06:17:45.992] [registry-api-akka.actor.default-dispatcher-3] [akka://registry-api/user/WebHookActor/WebHookActor-indexer-d79e025b-4833-43f0-a7e4-e5fb37262592] WebHook indexer Processing Some(190)-Some(200): STARTING
[INFO] [01/15/2019 06:17:46.383] [registry-api-akka.actor.default-dispatcher-12] [akka://registry-api/user/WebHookActor/WebHookActor-indexer-d79e025b-4833-43f0-a7e4-e5fb37262592] WebHook indexer Processing Some(190)-Some(200): DELIVERED
[INFO] [01/15/2019 06:17:46.391] [registry-api-akka.actor.default-dispatcher-7] [akka://registry-api/user/WebHookActor/WebHookActor-indexer-fa5cc0fd-e699-4824-9005-6f9bcf339d47] WebHook indexer Processing Some(190)-Some(200): DELIVERED
```

**Comment by mwu2018** [comment]
> Looks like it happens when the target restarts and reregisters itself:
> 
> ```
> [INFO] [01/15/2019 06:27:05.068] [registry-api-akka.actor.default-dispatcher-8] [akka://registry-api/user/WebHookActor/WebHookActor-indexer-0ca17046-9967-4d2a-bf5b-373484238a28] WebHook indexer Processing Some(2455)-Some(2465): STARTING
> [ERROR] [01/15/2019 06:27:05.236] [registry-api-akka.actor.default-dispatcher-8] [akka://registry-api/user/WebHookActor/WebHookActor-indexer-0ca17046-9967-4d2a-bf5b-373484238a28] WebHook indexer Processing Some(2455)-Some(2465): FAILED (akka.stream.StreamTcpException)
> [INFO] [01/15/2019 06:27:07.265] [registry-api-akka.actor.default-dispatcher-4] [akka://registry-api/user/WebHookActor/WebHookActor-indexer-0ca17046-9967-4d2a-bf5b-373484238a28] WebHook indexer Processing Some(2455)-Some(2465): STARTING
> [ERROR] [01/15/2019 06:27:07.529] [registry-api-akka.actor.default-dispatcher-8] [akka://registry-api/user/WebHookActor/WebHookActor-indexer-0ca17046-9967-4d2a-bf5b-373484238a28] WebHook indexer Processing Some(2455)-Some(2465): FAILED (akka.stream.StreamTcpException)
> [INFO] [01/15/2019 06:27:09.550] [registry-api-akka.actor.default-dispatcher-8] [akka://registry-api/user/WebHookActor/WebHookActor-indexer-0ca17046-9967-4d2a-bf5b-373484238a28] WebHook indexer Processing Some(2455)-Some(2465): STARTING
> [INFO] [01/15/2019 06:27:12.263] [registry-api-webhooks.AllWebHooksActor-dispatcher-13] [akka://registry-api/user/WebHookActor]     Creating new web hook actor for indexer.
> [INFO] [01/15/2019 06:27:14.287] [registry-api-akka.actor.default-dispatcher-8] [akka://registry-api/user/WebHookActor/WebHookActor-indexer-d9d90fea-b92d-4e26-a7e8-833aba02df28] WebHook indexer Processing Some(2455)-Some(2465): STARTING
> [INFO] [01/15/2019 06:27:19.049] [registry-api-akka.actor.default-dispatcher-8] [akka://registry-api/user/WebHookActor/WebHookActor-indexer-d9d90fea-b92d-4e26-a7e8-833aba02df28] WebHook indexer Processing Some(2455)-Some(2465): DELIVERED
> [INFO] [01/15/2019 06:27:19.050] [registry-api-akka.actor.default-dispatcher-4] [akka://registry-api/user/WebHookActor/WebHookActor-indexer-0ca17046-9967-4d2a-bf5b-373484238a28] WebHook indexer Processing Some(2455)-Some(2465): DELIVERED
> [INFO] [01/15/2019 06:27:21.069] [registry-api-akka.actor.default-dispatcher-10] [akka://registry-api/user/WebHookActor/WebHookActor-indexer-0ca17046-9967-4d2a-bf5b-373484238a28] WebHook indexer Processing Some(2465)-Some(2477): STARTING
> [INFO] [01/15/2019 06:27:21.069] [registry-api-akka.actor.default-dispatcher-7] [akka://registry-api/user/WebHookActor/WebHookActor-indexer-d9d90fea-b92d-4e26-a7e8-833aba02df28] WebHook indexer Processing Some(2465)-Some(2477): STARTING
> [INFO] [01/15/2019 06:27:21.765] [registry-api-akka.actor.default-dispatcher-10] [akka://registry-api/user/WebHookActor/WebHookActor-indexer-0ca17046-9967-4d2a-bf5b-373484238a28] WebHook indexer Processing Some(2465)-Some(2477): DELIVERED
> [INFO] [01/15/2019 06:27:21.854] [registry-api-akka.actor.default-dispatcher-4] [akka://registry-api/user/WebHookActor/WebHookActor-indexer-d9d90fea-b92d-4e26-a7e8-833aba02df28] WebHook indexer Processing Some(2465)-Some(2477): DELIVERED
> ```

Is it OK if I investigate this next week?

**Comment by AlexGilleran** [comment]
Yep, no rush!

**Comment by t83714** [comment]
@mwu2018 I think those logs were from registry API logs?
You probably can find them from registry API pod via `kubectl logs`?
By the way, the `webhookid` field on webhook table is an `unique` column.
Seems not possible to have more than one webhook records created for the same type?

**Comment by mwu2018** [comment]
I could not find similar log entries in
https://console.cloud.google.com/kubernetes/pod/asia-east1-a/dev-new/issue-749/registry-api-full-5f4d66c56b-c2ctm?project=terriajs&container_summary_list_tablesize=10&tab=details&duration=PT1H
Maybe I am looking at a wrong place?

**Comment by mwu2018** [comment]
I tried to reproduce the issue but failed.
1)Temporarily disable indexer
``` 
kubectl.exe --context gke_terriajs_asia-east1-a_dev-new --namespace=issue-749 scale --replicas=0 deployment/indexer
```
2) The indexer lastevent = 195050. I manually changed it to 195040.
3) Restart registry api. It will fail to send events 195040-195050 to the indexer.
4) Re-enable the indexer
```
kubectl.exe --context gke_terriajs_asia-east1-a_dev-new --namespace=issue-749 scale --replicas=1 deployment/indexer
```
The registry api will successfully deliver events 195040-195050 to the indexer. There are no any duplicates in the log. The log content follows.
[INFO] [01/21/2019 05:22:26.933] [main] [RegistryApp$(akka://registry-api)] Starting MAGDA Registry
[INFO] [01/21/2019 05:22:32.474] [registry-api-webhooks.AllWebHooksActor-dispatcher-9] [akka://registry-api/user/WebHookActor] Start to retry all inactive webhooks...
[INFO] [01/21/2019 05:22:32.918] [registry-api-webhooks.AllWebHooksActor-dispatcher-9] [akka://registry-api/user/WebHookActor] Skip retry Some(minion-format) as it is still in backoff time window. Last retry time: 2019-01-21T04:15:24.980Z..
[INFO] [01/21/2019 05:22:32.918] [registry-api-webhooks.AllWebHooksActor-dispatcher-9] [akka://registry-api/user/WebHookActor] Skip retry Some(minion-visualization) as it is still in backoff time window. Last retry time: 2019-01-21T04:15:24.980Z..
[INFO] [01/21/2019 05:22:32.919] [registry-api-webhooks.AllWebHooksActor-dispatcher-9] [akka://registry-api/user/WebHookActor] Invalidate Webhook Cache for retry List(indexer) inactive hooks...
[INFO] [01/21/2019 05:22:32.981] [registry-api-webhooks.AllWebHooksActor-dispatcher-9] [akka://registry-api/user/WebHookActor]    Added new hook indexer to DB.
[INFO] [01/21/2019 05:22:33.016] [registry-api-webhooks.AllWebHooksActor-dispatcher-13] [akka://registry-api/user/WebHookActor]     Creating new web hook actor for indexer.
[INFO] [01/21/2019 05:22:33.020] [registry-api-webhooks.AllWebHooksActor-dispatcher-13] [akka://registry-api/user/WebHookActor]     Creating new web hook actor for minion-format.
[INFO] [01/21/2019 05:22:33.024] [registry-api-webhooks.AllWebHooksActor-dispatcher-13] [akka://registry-api/user/WebHookActor]     Creating new web hook actor for minion-visualization.
[INFO] [01/21/2019 05:22:33.028] [registry-api-webhooks.AllWebHooksActor-dispatcher-13] [akka://registry-api/user/WebHookActor] Completed retry all inactive webhooks.
[INFO] [01/21/2019 05:22:35.415] [registry-api-akka.actor.default-dispatcher-5] [akka://registry-api/user/WebHookActor/WebHookActor-minion-format-e6ae2671-eb6a-48c3-8fe5-e8851479e154] WebHook minion-format: Up to date at event Some(182903)
[INFO] [01/21/2019 05:22:35.476] [registry-api-akka.actor.default-dispatcher-14] [akka://registry-api/user/WebHookActor/WebHookActor-minion-visualization-8ce7bc99-2c01-4c49-896e-404cd33abb75] WebHook minion-visualization: Up to date at event Some(182903)
[INFO] [01/21/2019 05:22:35.521] [registry-api-akka.actor.default-dispatcher-16] [akka://registry-api/user/WebHookActor/WebHookActor-indexer-a2e41294-2684-4f49-98f1-d78771d86c2e] WebHook indexer Processing Some(195040)-Some(195050): STARTING
[ERROR] [01/21/2019 05:22:46.676] [registry-api-akka.actor.default-dispatcher-5] [akka://registry-api/user/WebHookActor/WebHookActor-indexer-a2e41294-2684-4f49-98f1-d78771d86c2e] WebHook indexer Processing Some(195040)-Some(195050): FAILED (akka.stream.StreamTcpException)
[INFO] [01/21/2019 05:25:39.708] [registry-api-akka.actor.default-dispatcher-2] [akka://registry-api/user/WebHookActor/WebHookActor-indexer-a2e41294-2684-4f49-98f1-d78771d86c2e] WebHook indexer Processing Some(195040)-Some(195050): STARTING
[INFO] [01/21/2019 05:25:45.690] [registry-api-akka.actor.default-dispatcher-2] [akka://registry-api/user/WebHookActor/WebHookActor-indexer-a2e41294-2684-4f49-98f1-d78771d86c2e] WebHook indexer Processing Some(195040)-Some(195050): DELIVERED
[INFO] [01/21/2019 05:25:47.789] [registry-api-akka.actor.default-dispatcher-28] [akka://registry-api/user/WebHookActor/WebHookActor-indexer-a2e41294-2684-4f49-98f1-d78771d86c2e] WebHook indexer: Up to date at event Some(195050)
[INFO] [01/21/2019 05:25:49.814] [registry-api-akka.actor.default-dispatcher-2] [akka://registry-api/user/WebHookActor/WebHookActor-indexer-a2e41294-2684-4f49-98f1-d78771d86c2e] WebHook indexer: Up to date at event Some(195050)
[INFO] [01/21/2019 05:34:28.295] [registry-api-akka.actor.default-dispatcher-115] [akka://registry-api/user/WebHookActor/WebHookActor-indexer-a2e41294-2684-4f49-98f1-d78771d86c2e] WebHook indexer: Up to date at event Some(195050)
[INFO] [01/21/2019 05:34:28.308] [registry-api-akka.actor.default-dispatcher-118] [akka://registry-api/user/WebHookActor/WebHookActor-minion-format-e6ae2671-eb6a-48c3-8fe5-e8851479e154] WebHook minion-format: Up to date at event Some(182903)
[INFO] [01/21/2019 05:34:28.314] [registry-api-akka.actor.default-dispatcher-108] [akka://registry-api/user/WebHookActor/WebHookActor-minion-visualization-8ce7bc99-2c01-4c49-896e-404cd33abb75] WebHook minion-visualization: Up to date at event Some(182903)
[INFO] [01/21/2019 05:34:30.390] [registry-api-akka.actor.default-dispatcher-106] [akka://registry-api/user/WebHookActor/WebHookActor-minion-format-e6ae2671-eb6a-48c3-8fe5-e8851479e154] WebHook minion-format: Up to date at event Some(182903)
[INFO] [01/21/2019 05:35:26.488] [registry-api-akka.actor.default-dispatcher-131] [akka://registry-api/user/WebHookActor/WebHookActor-indexer-a2e41294-2684-4f49-98f1-d78771d86c2e] WebHook indexer: Up to date at event Some(195050)
[INFO] [01/21/2019 05:35:26.501] [registry-api-akka.actor.default-dispatcher-127] [akka://registry-api/user/WebHookActor/WebHookActor-minion-format-e6ae2671-eb6a-48c3-8fe5-e8851479e154] WebHook minion-format: Up to date at event Some(182903)
[INFO] [01/21/2019 05:35:26.502] [registry-api-akka.actor.default-dispatcher-106] [akka://registry-api/user/WebHookActor/WebHookActor-minion-visualization-8ce7bc99-2c01-4c49-896e-404cd33abb75] WebHook minion-visualization: Up to date at event Some(182903)
[INFO] [01/21/2019 05:35:28.531] [registry-api-akka.actor.default-dispatcher-127] [akka://registry-api/user/WebHookActor/WebHookActor-minion-visualization-8ce7bc99-2c01-4c49-896e-404cd33abb75] WebHook minion-visualization: Up to date at event Some(182903)
[INFO] [01/21/2019 05:35:54.181] [registry-api-akka.actor.default-dispatcher-140] [akka://registry-api/user/WebHookActor/WebHookActor-indexer-a2e41294-2684-4f49-98f1-d78771d86c2e] WebHook indexer: Up to date at event Some(195050)
[INFO] [01/21/2019 05:35:56.292] [registry-api-akka.actor.default-dispatcher-131] [akka://registry-api/user/WebHookActor/WebHookActor-indexer-a2e41294-2684-4f49-98f1-d78771d86c2e] WebHook indexer: Up to date at event Some(195050)

**Comment by mwu2018** [comment]
Here are steps to reproduce the issue.
1) The indexer lastevent = 195050. I manually changed it to 195030 in the database.
2) Delete pods indexer and registry-api at the same time:
```
kubectl.exe --context gke_terriajs_asia-east1-a_dev-new --namespace=issue-749 delete pod registry-api-full-5f4d66c56b-tjvqp indexer-7c65ffc744-h94z9
```
3) If the registry api starts running before the indexer, it will reproduce the issue, as in the log below
```
[INFO] [01/21/2019 06:04:41.926] [main] [RegistryApp$(akka://registry-api)] Starting MAGDA Registry
[INFO] [01/21/2019 06:04:47.340] [registry-api-webhooks.AllWebHooksActor-dispatcher-9] [akka://registry-api/user/WebHookActor] Start to retry all inactive webhooks...
[INFO] [01/21/2019 06:04:47.874] [registry-api-webhooks.AllWebHooksActor-dispatcher-9] [akka://registry-api/user/WebHookActor] Skip retry Some(minion-format) as it is still in backoff time window. Last retry time: 2019-01-21T04:15:24.980Z..
[INFO] [01/21/2019 06:04:47.876] [registry-api-webhooks.AllWebHooksActor-dispatcher-9] [akka://registry-api/user/WebHookActor] Skip retry Some(minion-visualization) as it is still in backoff time window. Last retry time: 2019-01-21T04:15:24.980Z..
[INFO] [01/21/2019 06:04:47.877] [registry-api-webhooks.AllWebHooksActor-dispatcher-9] [akka://registry-api/user/WebHookActor] Invalidate Webhook Cache for retry List(indexer) inactive hooks...
[INFO] [01/21/2019 06:04:47.890] [registry-api-webhooks.AllWebHooksActor-dispatcher-9] [akka://registry-api/user/WebHookActor]    Added new hook indexer to DB.
[INFO] [01/21/2019 06:04:47.914] [registry-api-webhooks.AllWebHooksActor-dispatcher-13] [akka://registry-api/user/WebHookActor]     Creating new web hook actor for indexer.
[INFO] [01/21/2019 06:04:47.916] [registry-api-webhooks.AllWebHooksActor-dispatcher-13] [akka://registry-api/user/WebHookActor]     Creating new web hook actor for minion-format.
[INFO] [01/21/2019 06:04:47.916] [registry-api-webhooks.AllWebHooksActor-dispatcher-13] [akka://registry-api/user/WebHookActor]     Creating new web hook actor for minion-visualization.
[INFO] [01/21/2019 06:04:47.917] [registry-api-webhooks.AllWebHooksActor-dispatcher-13] [akka://registry-api/user/WebHookActor] Completed retry all inactive webhooks.
[INFO] [01/21/2019 06:04:50.293] [registry-api-akka.actor.default-dispatcher-5] [akka://registry-api/user/WebHookActor/WebHookActor-minion-format-34965152-dee6-4800-99fa-144903b28f8d] WebHook minion-format: Up to date at event Some(182903)
[INFO] [01/21/2019 06:04:50.302] [registry-api-akka.actor.default-dispatcher-3] [akka://registry-api/user/WebHookActor/WebHookActor-minion-visualization-3b5a39d9-d6db-4cc1-993b-5984321b37b6] WebHook minion-visualization: Up to date at event Some(182903)
[INFO] [01/21/2019 06:04:50.380] [registry-api-akka.actor.default-dispatcher-16] [akka://registry-api/user/WebHookActor/WebHookActor-indexer-57697fbe-2a99-437f-9f5e-bfc9358ba73e] WebHook indexer Processing Some(195030)-Some(195040): STARTING
[ERROR] [01/21/2019 06:04:51.703] [registry-api-akka.actor.default-dispatcher-5] [akka://registry-api/user/WebHookActor/WebHookActor-indexer-57697fbe-2a99-437f-9f5e-bfc9358ba73e] WebHook indexer Processing Some(195030)-Some(195040): FAILED (akka.stream.StreamTcpException)
[INFO] [01/21/2019 06:05:07.799] [registry-api-akka.actor.default-dispatcher-15] [akka://registry-api/user/WebHookActor/WebHookActor-indexer-57697fbe-2a99-437f-9f5e-bfc9358ba73e] WebHook indexer Processing Some(195030)-Some(195040): STARTING
[INFO] [01/21/2019 06:05:12.785] [registry-api-akka.actor.default-dispatcher-18] [akka://registry-api/user/WebHookActor/WebHookActor-indexer-57697fbe-2a99-437f-9f5e-bfc9358ba73e] WebHook indexer Processing Some(195030)-Some(195040): DELIVERED
[INFO] [01/21/2019 06:05:14.888] [registry-api-akka.actor.default-dispatcher-27] [akka://registry-api/user/WebHookActor/WebHookActor-indexer-57697fbe-2a99-437f-9f5e-bfc9358ba73e] WebHook indexer Processing Some(195040)-Some(195050): STARTING
[INFO] [01/21/2019 06:05:15.678] [registry-api-akka.actor.default-dispatcher-3] [akka://registry-api/user/WebHookActor/WebHookActor-indexer-57697fbe-2a99-437f-9f5e-bfc9358ba73e] WebHook indexer Processing Some(195040)-Some(195050): DELIVERED
[INFO] [01/21/2019 06:05:17.779] [registry-api-akka.actor.default-dispatcher-3] [akka://registry-api/user/WebHookActor/WebHookActor-indexer-57697fbe-2a99-437f-9f5e-bfc9358ba73e] WebHook indexer: Up to date at event Some(195050)
[INFO] [01/21/2019 06:05:19.813] [registry-api-akka.actor.default-dispatcher-3] [akka://registry-api/user/WebHookActor/WebHookActor-indexer-57697fbe-2a99-437f-9f5e-bfc9358ba73e] WebHook indexer: Up to date at event Some(195050)
```

**Comment by mwu2018** [comment]
@AlexGilleran The problem of webhooks are being sent twice simultaneously is now resolved by the new commit.
```
[INFO] [01/22/2019 01:01:16.290] [registry-api-webhooks.AllWebHooksActor-dispatcher-225] [akka://registry-api/user/WebHookActor]     Creating new web hook actor for indexer.
[INFO] [01/22/2019 01:01:18.486] [registry-api-akka.actor.default-dispatcher-200] [akka://registry-api/user/WebHookActor/WebHookActor-indexer-369aee26-d659-4a4a-ac17-515c261be71a] WebHook indexer Processing Some(195040)-Some(195050): STARTING
[INFO] [01/22/2019 01:01:22.114] [registry-api-akka.actor.default-dispatcher-217] [akka://registry-api/user/WebHookActor/WebHookActor-indexer-369aee26-d659-4a4a-ac17-515c261be71a] WebHook indexer Processing Some(195040)-Some(195050): DELIVERED
[INFO] [01/22/2019 01:01:24.184] [registry-api-akka.actor.default-dispatcher-230] [akka://registry-api/user/WebHookActor/WebHookActor-indexer-369aee26-d659-4a4a-ac17-515c261be71a] WebHook indexer: Up to date at event Some(195050)
```

**Comment by AlexGilleran** [comment]
Works good, doesn't fail liveness checks even when I set the max CPU to 100m, great work @mwu2018 😄

**Pull request merged**
