### PR TITLE
#1760 Home page items are configurable

### LINKED ISSUE #1760: Make homepage details come from content api
### Problem description
Currently all of the presentation stuff on the homepage (backgrounds, stories, tagline) is hard coded into the client. These details should live in the content api so they can be edited. This doesn't involve putting together a UI to edit them, just making them configurable by directly editing the database.

### Acceptance Criteria
- Home page tagline text is configurable
- Backgrounds (plus their associated searches) are configurable
- Home page stories are configurable
- Reasonable defaults for new installs - which presumably means a generic tagline, one generic background, no homepage stories at all (i.e. they're hidden)
- An upgrade path for search.data.gov.au - presumably an SQL script to run before upgrading

### PR DESCRIPTION
**Pull request by nahidakbar**
### What this PR does

Fixes #1760

### Checklist

-   [x] There are unit tests to verify my changes are correct or unit tests aren't applicable
-   [x] I've updated CHANGES.md with what I changed.
-   [x] I've linked this PR to an issue in ZenHub (core dev team only)

### CODE REVIEW

**Comment by t83714** [comment]
@nahidakbar Good jobs~ 🎉 

Had a play on Gitlab and found some minor things:

1> Default config shows a `0` char output on the homepage
untitled
2> Was trying to import DTA upgrade SQL script to checkout existing homepage functions (as default view won't show the stories). It seems we have some minor issue with the SQL script:
- This one: INSERT INTO public.content VALUES ('home/highlight-images/1540292158520/720w': reports ERROR:  unterminated quoted string at or near "'/9j/4AAQSkZJRgABAgEAJAAkAAD/
- Reports: 
```
ERROR:  duplicate key value violates unique constraint "content_pkey"
DETAIL:  Key (id)=(home/tagline/desktop) already exists. 
```
& 
```
ERROR:  duplicate key value violates unique constraint "content_pkey"
DETAIL:  Key (id)=(home/tagline/mobile) already exists.
```

**Comment by t83714** [comment]
@nahidakbar 

Had a play on DTA version homepage using upgrade SQL and works well 👍 

Only one minor inconsist thing I can find is the mobile version:

The default mobile view height seems much shorter than the current DTA version. 

Because of that, the `Latest News` button is blended into the purple footer background.

See screenshots below. the first one is the current branch and the second one is search.data.gov.au:

image

image

**Comment by nahidakbar** [comment]
Hmm that's a problem because the thing that introduces that bug fixes another issue:

image

Things looking ugly/blank when there is not content.

**Comment by t83714** [comment]
We need to merge this PR earlier as it's blocking other PRs created.
I've created two issues (#1811 #1812 ) for any related issues.

**Pull request merged**
