### PR TITLE
Issue/2261 New dropdown box design on `Dataset details and contents` page 

### LINKED ISSUE #2261: Details And Contents Page - Item 1 New Dropdown Box Design
Applied new design to all dropdown box on `Details And Contents Page`.

See screenshot below:

image

Estimate: 1-3

Update on 1st July 2019:

Based on the a11s discussion with @alyce & @AlexGilleran, we gonna use this component instead of using our own design:

https://jedwatson.github.io/react-select/

image
image

- One extra requirement: make tags looks like our design. i.e.

Make 

image

looks like 
image

### PR DESCRIPTION
**Pull request by t83714**
### What this PR does

Fixes #2261 

image

- Default to `English` if nothing is selected
- Implemented with buttons as select options to make sure it's a11s compliant
- Will auto scroll to the first selected element on initial render only (So user won't be confused about its selection status)
- Didn't implement the scroll design as we only have very limit browser support on this.

#### Tech side review notes:

Have to introduce a polyfill (smoothscroll-polyfill) to make sure this scroll spec  http://iamdustan.com/smoothscroll/ to supported down to IE9

#### Test Site:

https://issue-2261.dev.magda.io/dataset/add

### Checklist

-   [x] unit tests aren't applicable
-   [x] I've updated CHANGES.md with what I changed.
-   [x] I've linked this PR to an issue in ZenHub (core dev team only)

### CODE REVIEW

**Comment by t83714** [comment]
Based on a11s feedback, we're gonna update this PR and change the design of this control to:
https://semantic-ui.com/modules/dropdown.html
See issue description for more details.

**Comment by t83714** [comment]
It's now replaced with new dropdown ctrl now.
image
@AlexGilleran @alyce Please have a look again~
To @alyce It's now full width on screen and I will leave the width adjustment to the `whole page adjustment` ticket as now most other ctrls haven't been done yet and may change.

**Comment by t83714** [comment]
a11y feedback from @alyce :
We should be able to use `tab` key to navigate to the `remove` button (the `x` icon) and press `enter` key to remove the tag

**Comment by t83714** [comment]
@alyce 
Please have a look again.
You can reach the remove buttons by pressing `tab` key and press `enter` to remove item now.
Test site URL see issue description above.

**Comment by alyce** [comment]
> @alyce
> Please have a look again.
> You can reach the remove buttons by pressing `tab` key and press `enter` to remove item now.
> Test site URL see issue description above.

@t83714 looks good, thank you!

**Pull request merged**
