### PR TITLE
Upgrade terria-server to the latest version

### LINKED ISSUE #1661: Upgrade TerriaJS Server
### Problem description
Our Terria friends just published a vulnerability in Terria server, which we use:

https://medium.com/terria/security-vulnerability-in-terriajs-server-82c8bf4da0a5

We should upgrade so we're not vulnerable either.

### Acceptance Criteria
The preview-map server is running terriajs-server 2.7.4 or above.

### PR DESCRIPTION
**Pull request by AlexGilleran**
### What this PR does
TerriaJS just published a vulnerability in their server, which we're (kinda) vulnerable too as well, so we should patch it ASAP.

This also fixes the full preview failing (although it takes 30 minutes to start :() and makes HTTPS preview urls stop displaying the default backend.

Fixes #1661 

### Checklist

-   [x] There are unit tests to verify my changes are correct or unit tests aren't applicable
-   [x] I've updated CHANGES.md with what I changed.
-   [x] I've linked this PR to an issue in ZenHub (core dev team only)
-   [x] I've assigned this PR to someone (if you don't know who to assign it to, pick @AlexGilleran)

### CODE REVIEW

**Comment by t83714** [comment]
👍 to preview https

**Comment by AlexGilleran** [comment]
Trying to put a test together for this vulnerability 😬

**Comment by AlexGilleran** [comment]
Ah jeez. Yeah I think I updated some stuff I shouldn't have when I upgraded terria 😬.

In the mean time, here's the proof of this thing - so I've made a site at http://nyan.search.data.gov.au that redirects to http://nyan.cat.

If you request this through http://search.data.gov.au/preview-map/proxy/http://nyan.search.data.gov.au then it proxies the redirected site (bad).

If you do the same to my branch: http://1661-upgrade-terria.dev.magda.io/preview-map/proxy/http://nyan.search.data.gov.au then it passes through the redirect (good).

**Comment by t83714** [comment]
Thanks for the `nyan.cat` redirection test~ It's really eye-catching 😆 Will save it for my future redirection target~
💯 It works well~ The preview site is no longer proxy through the content anymore.
Also, had a play on dev site for preview map function. 
Works well~ 💯 
Only thing is KML/KMZ source ---- we properly want to open an issue on terria to update the `Madgacatelog`?
Other than that all good~

**Comment by AlexGilleran** [comment]
@t83714 I've merged the latest `MagdaCatalogItem` and our latest together and slain some build krakens, should be ok to look at again now.

**Comment by t83714** [comment]
Good Job 👍 the build problem is hard to fix sometimes indeed~ Travis works well now~ 💯 
Had test dataset:
https://1661-upgrade-terria.dev.magda.io/dataset/ds-sa-b3238d77-5866-434a-8360-fb9a22c001cf/details
on gitlab site. 
The KMZ map works well.
The only problem is the national map button will report an unsupported format error. But that requires an update on `national map` project and should be solved by a separate issue.
Merged this PR now~

**Pull request merged**
