### PR TITLE
Mobile search

### PR DESCRIPTION
**Pull request by chloeleichen**
### What this PR does

mobile searchbox change into purple:
screen shot 2018-07-05 at 1 13 19 pm

### Checklist

-   [x] There are unit tests to verify my changes are correct | Unit tests aren't applicable (delete one)
-   [x] I've updated CHANGES.md with what I changed.
-   [x] I've linked this PR to an issue in ZenHub (or there is no issue) and dragged it to the _Pull Request_ column
-   [x] There are sufficient comments for my code to be understandable - and I realise reviewers will pull me up on it if not!

### CODE REVIEW

**Comment by AlexGilleran** [comment]
Looks like this to me: 
image

Kinda hard to read the text.

**Comment by chloeleichen** [comment]
@AlexGilleran that's placeholder text and its the same color as the placeholder on desktop, do we want to make it whiter on both desktop and mobile @tkeuneman

**Comment by chloeleichen** [comment]
screen shot 2018-07-06 at 4 05 59 pm

Updated placeholder color on mobile only

**Comment by AlexGilleran** [comment]
@chloeleichen now the placeholder is great on the search results screen but invisible on the home page 😋 

image

**Pull request merged**
