### PR TITLE
Issue/2250 Add dataset progress meter

### LINKED ISSUE #2250: Align "Add a Dataset" progress meter
### Problem description
Align the progress meter at the top of the "Add a Dataset" flow to match the new designs

image
image
https://app.zeplin.io/project/5cff0c2b6308535da4f2dfe8/screen/5cff0cef79c3825e2e5cb58c

### Acceptance Criteria
- Should be changed for all parts of the "Add a Dataset" flow that it appears on (see other Zeplin screens)
- User should be able to click on a step that they've already completed to go back there
- User should _not_ be able to click on a step that they haven't been to yet
- Steps that the user has already completed should have a tick (see picture)

### PR DESCRIPTION
**Pull request by t83714**
### What this PR does

Fixes #2250 
- Add dataset progress meter

~#2249 has been merged into that probably merge [this PR](https://github.com/magda-io/magda/pull/2255) first~
This PR includes #2249 as well

Test Site:
https://issue-2250.dev.magda.io/

### Checklist

-   [x] unit tests aren't applicable
-   [x] I've updated CHANGES.md with what I changed.
-   [x] I've linked this PR to an issue in ZenHub (core dev team only)

### CODE REVIEW

**Comment by AlexGilleran** [comment]
Nice work - looks like the title of the progress meter should say "Add a dataset" according to the designs rather than saying the name of the current step?

image

**Comment by t83714** [comment]
> Nice work - looks like the title of the progress meter should say "Add a dataset" according to the designs rather than saying the name of the current step?
> 
> image

I think you are right. Made it fixed title now~

**Comment by t83714** [comment]
@AlexGilleran this is ready to have a look again~
I also updated the new version icons~

**Comment by AlexGilleran** [comment]
@t83714 the title looks good now but I'm pretty sure the progress bar should align with the rest of the page rather than being full width:

image

i.e. "Add a dataset should be lined up with "Magda has reviewed your files and pre-populated the metadata fields based on the contents"

**Comment by t83714** [comment]
@AlexGilleran 
The alignment of the progress content has been adjusted and deployed.
You can check from: https://issue-2250.dev.magda.io/dataset/add/files

**Comment by AlexGilleran** [comment]
Thanks @t83714 - sorry to be annoying but it looks like the Next: buttons are broken now :(

image

They should have the next page on them!

**Comment by t83714** [comment]
@AlexGilleran 
Thanks for it~ I did miss it when refactoring the page layout 😄 
It's now fixed

**Pull request merged**
