### PR TITLE
Add organisation ignore filter to CKAN connector

### PR DESCRIPTION
**Pull request by maxious**
### What this PR does

Add organisation ignore filter to CKAN connector and change organisation white list to be a list not a single organisation name for consistency.

### Checklist

-   [x] There are unit tests to verify my changes are correct or unit tests aren't applicable
-   [x] I've updated CHANGES.md with what I changed.
-   [ ] I've linked this PR to an issue in ZenHub (core dev team only)

### CODE REVIEW

**Comment by AlexGilleran** [comment]
Tested it on https://ckan-org-ignore-filter.dev.magda.io with this configuration:

```

connectors:
  config:
    - image:
        name: magda-ckan-connector
      id: dga
      name: data.gov.au
      sourceUrl: https://data.gov.au/
      pageSize: 1000
      ignoreHarvestSources:
        - "*"
      ignoreOrganisationNames:
        - "Bioregional Assessment Programme"
        - "State of the Environment"
```

But looks like it's successfully filtering out Bioregional Assessment Programme but not State of the Environment?

Connector log looks like this:
```
Requesting https://data.gov.au/api/3/action/organization_list?all_fields=true&include_users=true&include_groups=true&include_extras=true&include_tags=true&offset=0&limit=1000
Received@0
Requesting https://data.gov.au/api/3/action/organization_list?all_fields=true&include_users=true&include_groups=true&include_extras=true&include_tags=true&offset=407&limit=1000
Received@407
Requesting https://data.gov.au/api/3/action/package_search?sort=metadata_created+asc&start=0&rows=1000&fq=-organization:%22Bioregional%20Assessment%20Programme%22%20-organization:%22State%20of%20the%20Environment%22%20-harvest_source_title:*
Received@0
Requesting https://data.gov.au/api/3/action/package_search?sort=metadata_created+asc&start=1000&rows=1000&fq=-organization:%22Bioregional%20Assessment%20Programme%22%20-organization:%22State%20of%20the%20Environment%22%20-harvest_source_title:*
Received@1000
Requesting https://data.gov.au/api/3/action/package_search?sort=metadata_created+asc&start=2000&rows=1000&fq=-organization:%22Bioregional%20Assessment%20Programme%22%20-organization:%22State%20of%20the%20Environment%22%20-harvest_source_title:*
Received@2000
Requesting https://data.gov.au/api/3/action/package_search?sort=metadata_created+asc&start=3000&rows=1000&fq=-organization:%22Bioregional%20Assessment%20Programme%22%20-organization:%22State%20of%20the%20Environment%22%20-harvest_source_title:*
Received@3000
Requesting https://data.gov.au/api/3/action/package_search?sort=metadata_created+asc&start=4000&rows=1000&fq=-organization:%22Bioregional%20Assessment%20Programme%22%20-organization:%22State%20of%20the%20Environment%22%20-harvest_source_title:*
Received@4000
Aspect Definitions Connected: 12
Datasets Connected: 4927
Distributions Connected: 12854
Organizations Connected: 407
Records Trimmed: 0
```

@t83714 mentioned that he could never get multiple orgs to work at the same time for inclusion, you might be running into the same (but inverse, obviously) problem.

**Comment by maxious** [comment]
Slight CKAN nuance, org names (the only thing you can solr search on) are actually URL slugs.

4928 rows: https://data.gov.au/api/3/action/package_search?sort=metadata_created+asc&start=0&rows=0&fq=-organization:%22Bioregional%20Assessment%20Programme%22%20-harvest_source_title:*
3233 rows: https://data.gov.au/api/3/action/package_search?sort=metadata_created+asc&start=0&rows=0&fq=-organization:%22bioregional-assessment-programme%22%20-harvest_source_title:*

Seperating blacklists with spaces (assumed AND) works:
4902 rows: https://data.gov.au/api/3/action/package_search?sort=metadata_created+asc&start=0&rows=0&fq=-organization:%22doee%22%20-harvest_source_title:*
4586 rows: https://data.gov.au/api/3/action/package_search?sort=metadata_created+asc&start=0&rows=0&fq=-organization:%22doee%22%20-organization:%22abares%22%20-harvest_source_title:*

But not for inclusion, you need explicit OR (or change solr settings -not happening):
0 rows (no dataset can have 2 orgs in CKAN): https://data.gov.au/api/3/action/package_search?sort=metadata_created+asc&start=0&rows=0&fq=organization:%22bioregional-assessment-programme%22%20organization:abares%20%20-harvest_source_title:*
2022 rows: https://data.gov.au/api/3/action/package_search?sort=metadata_created+asc&start=0&rows=0&fq=(organization:%22bioregional-assessment-programme%22%20%20OR%20organization:abares%20%20OR%20organization:digital-transformation-agency)%20-harvest_source_title:*

I'll try fixing the inclusion case

**Comment by t83714** [comment]
Didn't realise you can use `(`, `)` and `OR` in `fq`~
@maxious That's awesome~ 👍

**Comment by maxious** [comment]
@AlexGilleran I've added support for multiple included CKAN orgs and a test

**Pull request merged**
