### PR TITLE
STEPHEN Home Page Test (21 Sept)

### PR DESCRIPTION
**Pull request by stephencannings**
### What this PR does

TEST only, home page.

### CODE REVIEW

**Comment by stephencannings** [comment]
The page is incomplete... (like it has no css)
https://stephencannings-patch-12.dev.magda.io/

@alex and @maxious what am I missing here? Thanks for your help.

image

**Comment by t83714** [comment]
@stephencannings 
We recently moved the main CSS file to a new content API.
The `Preview (UI only)` option will only deploy one web server pod (without the content API).
Therefore, the main CSS file was failed to be downloaded.
I've created an issue for this (#1730) 
In the meantime, you can use the `(No Data) Run As Preview` option to preview your home page changes (as that option will deploy a content API pod)

**Comment by stephencannings** [comment]
Thank you @t83714 !

**Comment by maxious** [comment]
https://stephencannings-patch-12.dev.magda.io/ works now

**Pull request closed without merging**
