### PR TITLE
Filter bug

### PR DESCRIPTION
**Pull request by chloeleichen**
### What this PR does

Fixed a bug in search filter that causes the filter to be irresponsive 
### Checklist

-   [x] There are unit tests to verify my changes are correct | Unit tests aren't applicable (delete one)
-   [x] I've updated CHANGES.md with what I changed.
-   [x] I've linked this PR to an issue in ZenHub (or there is no issue) and dragged it to the _Pull Request_ column
-   [x] There are sufficient comments for my code to be understandable - and I realise reviewers will pull me up on it if not!

### CODE REVIEW

**Comment by t83714** [comment]
@chloeleichen 
Works very well on other filters except for Region Filter panel
When you keep click on region map, sometimes you could end up select more than one region --- and if that happens, `Apply` button will do nothing if you click it
image

**Comment by chloeleichen** [comment]
@t83714 should be fixed now

**Comment by t83714** [comment]
@chloeleichen 
It seems you can enter a state that Date filter panel cannot be open (nothing happened when you click). Here is a link to re-produce:
https://filter-bug.dev.magda.io/search?organisation=Bureau%20of%20Mineral%20Resources%2C%20Geology%20and%20Geophysics&organisation=Commonwealth%20of%20Australia%20%28Geoscience%20Australia%29&organisation=Geoscience%20Australia&q=%2A&regionId=7&regionType=STE

**Comment by t83714** [comment]
tested on gitlab & works well 
Thanks @chloeleichen 👍

**Pull request merged**
