### PR TITLE
Fixes typo `publich`, also seen on magda.io.

### PR DESCRIPTION
**Pull request by nghamilton**
Fixes `publich` typo.

### CODE REVIEW

**Comment by AlexGilleran** [comment]
Thanks @nghamilton  - I know it's a bit ridiculous for a typo but could you sign the CLA? Happy to merge it then :)

**Comment by nghamilton** [comment]
Totally understandable. I believe the CLA should already have been signed
as of yesterday?

**Comment by AlexGilleran** [comment]
Doesn't look like it, maybe CLA-Assistant is just going slow :(.

**Comment by nghamilton** [comment]
I double-checked and I have signed it, but clicking the `Let us recheck it.`  CLA link doesn't update it, so it sounds like a delay with the assistant.

**Comment by AlexGilleran** [comment]
All good now :) :shipit:

**Pull request merged**
