### PR TITLE
CSW mappings to capture persistent URL and licences for GA

### LINKED ISSUE #1997: Fix Licenses for GA ECAT CSW Responses
### Problem description
GA have a new CSW endpoint at https://ecat.ga.gov.au/geonetwork/srv/eng/csw. However when Magda connects to it the licenses aren't getting through, although they are in there (https://ecat.ga.gov.au/geonetwork/srv/eng/csw?service=CSW&request=GetRecords&version=2.0.2&outputSchema=http://standards.iso.org/iso/19115/-3/mdb/1.0&resultType=results&elementSetName=full&startPosition=1&maxRecords=5). Presumably this is because they're in a new place, we should modify the CSW Connector to check that place for licenses.

### Problem reproduction steps
Point a CSW connector at https://ecat.ga.gov.au/geonetwork/srv/eng/csw

### PR DESCRIPTION
**Pull request by maxious**
### What this PR does

Fixes #1997 

Aside from adding more JSON queries for metadata matching, this also adds an example test for the new Geoscience Australia profile which requires some changes to the CSW queries. Also added an option to save query raw XML to a folder to help debug that functionality.

It is likely the metadata mapping will also benefit other CSW sources.

### Checklist

-   [x] There are unit tests to verify my changes are correct or unit tests aren't applicable
-   [x] I've updated CHANGES.md with what I changed.
-   [x] I've linked this PR to an issue in ZenHub (core dev team only)

### CODE REVIEW

**Comment by AlexGilleran** [comment]
@maxious looks like it's running fine now but it's failing to write the `dataset-publisher` aspect for most records - see https://1997-fix-ga-csw-metadata.dev.magda.io/dataset/ds-ga-a05f7892-bfcd-7506-e044-00144fdd4fa6/details?q= and its api call https://1997-fix-ga-csw-metadata.dev.magda.io/api/v0/registry/records/ds-ga-a05f7892-bfcd-7506-e044-00144fdd4fa6?dereference=true&aspect=dcat-dataset-strings&optionalAspect=dcat-distribution-strings&optionalAspect=dataset-distributions&optionalAspect=temporal-coverage&optionalAspect=dataset-publisher&optionalAspect=source&optionalAspect=source-link-status&optionalAspect=dataset-quality-rating. The `publisher` part of `dcat-dataset-strings` is fine but there's no `dataset-publisher` at all, hence the search doesn't get one :(.

**Comment by maxious** [comment]
Hmm I'll compare a bit with https://1997-fix-ga-csw-metadata.dev.magda.io/api/v0/registry/records/ds-tern-03312acf-5f95-4fcc-9802-52801afe4e85?dereference=true&aspect=dcat-dataset-strings&optionalAspect=dcat-distribution-strings&optionalAspect=dataset-distributions&optionalAspect=temporal-coverage&optionalAspect=dataset-publisher&optionalAspect=source&optionalAspect=source-link-status&optionalAspect=dataset-quality-rating from TERN and see if it can be improved.

**Comment by AlexGilleran** [comment]
It looks like the new code for CSW is able to find the name of the publisher in the right place but it's still looking for the rest of the publisher details in the old place :(.

**Comment by maxious** [comment]
@AlexGilleran fixed up the publisher and made the GA test examples a little more diverse 👍

**Pull request merged**
