### PR TITLE
Issue/1730 Gitlab UI only Preview should load CSS from external content API

### LINKED ISSUE #1730: Gitlab Preview (UI Only) Should load CSS file from remote content API
### Problem description

Currently, the main UI CSS is downloaded from the content API.

This causes some issue to Gitlab UI Only Preview as `UI only preview` will not deploy a content API pod in the cluster.

We should probably add a new configuration option to `web-server` chart so that the CSS URL can be specified when deploys the `web-server` pod.

Alternatively, we probably can update the CSS URL in frontend JS code.

### Problem reproduction steps

Create a new branch & try the Gitlab `Preview (UI Only)` function.

### PR DESCRIPTION
**Pull request by t83714**
### What this PR does

Fixes #1730 

# Test URL:

https://issue-1730.dev.magda.io/

### Checklist

-   [x] unit tests aren't applicable
-   [x] I've updated CHANGES.md with what I changed.
-   [x] I've linked this PR to an issue in ZenHub (core dev team only)
-   [ ] I've assigned this PR to someone (if you don't know who to assign it to, pick @AlexGilleran)

### CODE REVIEW

**Comment by AlexGilleran** [comment]
Doesn't this still have the issue that if you change the CSS and preview it, it'll still show the old CSS?

**Comment by t83714** [comment]
Yes. It won't fix that. We probably need a better solution for its `preview` purpose.
How about, instead of pointing main.css to dev.magda.io content api, adding a new configuration option to web server chart (probably call `useLocalStyleSheet`)?
When it's true, we just make web client load pre-built static main.css from `build` folder?

**Comment by AlexGilleran** [comment]
Sounds good!

**Comment by t83714** [comment]
@AlexGilleran It's ready to have another look~
The test site `https://issue-1730.dev.magda.io/` is deployed using option `no data` you can tell the CSS is loaded from the content API.
If you re-deploy it using UI only option, you will find the prebuild local CSS file is used.

**Pull request merged**
