### PR TITLE
Issue/2251 File upload area

### LINKED ISSUE #2251: Align "Add files" part of "Add dataset" flow to designs
### Problem description
Align the "Add files" screen in the add a dataset flow with the designs:

image
https://app.zeplin.io/project/5cff0c2b6308535da4f2dfe8/screen/5cff0cef79c3825e2e5cb58c
image
https://app.zeplin.io/project/5cff0c2b6308535da4f2dfe8/screen/5cff0cf12d682519cad8abeb

### Needs clarification
- What should it look like when you edit a file?

### Acceptance Criteria
- These two designs are unified into one screen, as happens now - once dragged and dropped the file should display a progress bar until analysis has finished, then display the summary as seen in the second picture/link
- The "X" to remove a file should also be present once the analysis has been finished

### PR DESCRIPTION
**Pull request by t83714**
### What this PR does

Fixes #2251 

File upload area

Better merge PR for #2250 first

### Checklist

-   [x] unit tests aren't applicable
-   [x] I've updated CHANGES.md with what I changed.
-   [x] I've linked this PR to an issue in ZenHub (core dev team only)

### CODE REVIEW

**Comment by t83714** [comment]
The file upload area 
image
need to be able to select by press `tab` key

**Comment by t83714** [comment]
@alyce the a11y issue has been fixed
image
You can go to https://issue-2251.dev.magda.io/dataset/add/files to have a look~
Can't find any standard way to fix it --- it's probably a hack (there is an invisible button cover it) but works fine~
Let me know your idea~

**Comment by AlexGilleran** [comment]
image
### Drop zone
This looks like it's gone to some kind of Times New Roman-esque font, but it should be the standard sans serif one?

### Added file box
image
vs.
image

- Background looks like it should be a shade of grey?
- I think the buttons in the corner should be further over to the right
- The Labels ("Format", "Size", "Last Modified") should be bold

### Hint
image
I said we shouldn't worry about this before, but looking at it all now it seems like it's quite helpful

### Loading State
image
vs 
image

- The design has the title on the same level as the "X" in the corner
- The title needs to be truncated so it doesn't overlap the "X"
- I thought we were going to use icons from the dataset page? If not we need to correct the font in those icons, it's serif but it should be sans-serif

**Comment by alyce** [comment]
Screen Shot 2019-06-24 at 1 41 45 pm

I also think when you go into edit the file, you should be able to edit the file name directly

**Comment by t83714** [comment]
> image
> 
> ### Drop zone
> This looks like it's gone to some kind of Times New Roman-esque font, but it should be the standard sans serif one?
> 
> ### Added file box
> image
> vs.
> image
> 
> * Background looks like it should be a shade of grey?
> * I think the buttons in the corner should be further over to the right
> * The Labels ("Format", "Size", "Last Modified") should be bold
> 
> ### Hint
> image
> 
> I said we shouldn't worry about this before, but looking at it all now it seems like it's quite helpful
> ### Loading State
> image
> vs
> image
> 
> * The design has the title on the same level as the "X" in the corner
> * The title needs to be truncated so it doesn't overlap the "X"
> * I thought we were going to use icons from the dataset page? If not we need to correct the font in those icons, it's serif but it should be sans-serif

@AlexGilleran 
- the whole dropbox area is an image (including text) 😄 --- I probably manually remove the text and add text back in.
- I initially used the dataset page icon but just really there is another widget on the 2nd page using similar icons. Thought to reuse the component (only update the icon and make it smaller font if large than 4 chars) to make it consistent.

Do you think the following icons look alright? If ok, I probably can change back --- the current way of generating icons indeed a hack 😄  

image

**Comment by t83714** [comment]
> Screen Shot 2019-06-24 at 1 41 45 pm
> 
> I also think when you go into edit the file, you should be able to edit the file name directly

@alyce It's a good idea to add the editing name function 😄 
Do you think it's better replace the current format input box with file name or ajdust the size of the box and add an extra file name input?

**Comment by alyce** [comment]
@t83714 could we please just adjust the size of the box and add the extra file name input? :)

**Comment by t83714** [comment]
@alyce no problem~ will do that 👍

**Comment by t83714** [comment]
- adjusted drop zone svg font
- adjusted file box background, button position & font
- Added Hint text
- adjusted file icon font
- adjusted loading file box button position
- Added edit file name ctrl
- style adjustment for bigger file box

**Comment by AlexGilleran** [comment]
> Do you think the following icons look alright? If ok, I probably can change back --- the current way of generating icons indeed a hack 😄

I think that looks really good tbh - what do you think @alyce ?

Apart from that looks pretty good - my last nit-pick is that when you hover over the edit/close buttons the icon jumps down a tiny bit to make way for the border, it probably shouldn't move:

image

**Comment by t83714** [comment]
@AlexGilleran 
The `edit/close buttons jumping (when hovering)` issue has been fixed.

@AlexGilleran & @alyce 

For your reference, here is how our built-in icons looks like:

image 

Re: the icon issue, on the tech side, I think also prefer a non-hack way if we have an option 😄 
While working on the PR, I tried to improve the `icon SVG component` and make it cover more edging cases --- I feel like it probably not a sustainable option because:
- You have limited support within `SVG`. Probably can never solve all issues
- Update the icon are difficult and require more knowledge of hand-coding SVG

Do you guys think if we can opt to the following approach if we really want to 100% stick to the current design:
- Manual create SVG images for the following common formats (CSV, image etc)
- Design a generic SVG image to be used for all unrecognized/uncommon format

**Comment by AlexGilleran** [comment]
> Do you guys think if we can opt to the following approach if we really want to 100% stick to the current design:

    > Manual create SVG images for the following common formats (CSV, image etc)
    > Design a generic SVG image to be used for all unrecognized/uncommon format

I think whatever we're doing for the dataset page re: existing images and default images is fine 🤷‍♂

**Comment by t83714** [comment]
@AlexGilleran 
👍 Would probably change to the dataset page icons and let you know~

**Comment by alyce** [comment]
@t83714 I do quite like your idea of having a generic SVG image for unrecognised formats/uncommon types

**Comment by t83714** [comment]
@AlexGilleran 
The file icons have been updated.
Please have a look again~

**Pull request merged**
